### ISSUE TITLE
Reduce bundle / build size

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#66]
Currently the build size is over 400kb! Preact should be tiny, I am not sure why this is so big. Try reduce the bundle size by optimising imports. Alternatively find out what is taking so much space!

**Comment by c-w** [comment]
I did a bit of digging into this and it seems linked to the [react-octicons](https://github.com/ivanseed/gitstats/blob/0038058c7497a00328265abc561d3448f387d40d/package.json#L36) dependency. Removing that dependency drops the bundle-size to 215kb.

I hypothesize that this is because react-octoicons pulls in react and somehow this is not being optimized by the preact build. I'm not very familiar with preact so I don't know how to work around this. However, given that this project is using fairly few of the octoicons, one easy option to reduce the build size is to  inline the code for the icons. I'll open a pull request for this shortly.

**Comment by ivanseed** [comment]
Resolved by #72
